name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 7.4
          - 8.0
          - 8.1
          - 8.2

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}
          tools: cs2pr

      - name: Install dependencies with Composer
        uses: ramsey/composer-install@v2

      - name: Run PHPUnit
          run: |
            export $ENV
            vendor/bin/phpunit --coverage-clover=coverage.xml

      - name: Upload coverage file
          uses: actions/upload-artifact@v3
          with:
            name: phpunit-${{ matrix.deps }}-${{ matrix.php-version }}.coverage
            path: coverage.xml